### ISSUE TITLE
Question about A record 

### ISSUE THREAD

**Issue by Jbone187** [Infoblox-Development/Infoblox-API-Python#30]
I have been looking all over the internet and haven't found a way to create a A record with the wapi. I have only seen how to create a host. Just to verify to your knowledge do you just use a host as a A record?

**Comment by armsby** [comment]
A record can be created like this:
curl -k -u admin:infoblox -H 'content-type: application/json' -X POST "https://gridmaster/wapi/v2.11/record:a?_return_fields%2B=name,ipv4addr&_return_as_object=1" -d
'{"name":"server.info.com","ipv4addr":"10.10.10.2"}'

**Comment by Jbone187** [comment]
I get this error when I try that:

{ "Error": "AdmConDataError: None (IBDataConflictError: IB.Data.Conflict:The action is not allowed. A parent was not found.)", 
  "code": "Client.Ibap.Data.Conflict", 
  "text": "The action is not allowed. A parent was not found."

**Comment by Jbone187** [comment]
I got it to work ty

**Comment by martinbarlow** [comment]
I also got the **"text": "The action is not allowed. A parent was not found."** error. If you remember the solution, would be nice if you could post it.
